import productImg from "../assets/ProductCard/product-cover-5 (1).png";

const cartData = {
  products: [
    {
      id: 1,
      image: productImg,
      title: "Graphic Design",
      department: "English Department",
      price: "$16.48",
      salePrice: "$6.48",
    },
    {
      id: 1,
      image: productImg,
      title: "Graphic Design",
      department: "English Department",
      price: "$16.48",
      salePrice: "$6.48",
    },
    {
      id: 1,
      image: productImg,
      title: "Graphic Design",
      department: "English Department",
      price: "$16.48",
      salePrice: "$6.48",
    },
    {
      id: 1,
      image: productImg,
      title: "Graphic Design",
      department: "English Department",
      price: "$16.48",
      salePrice: "$6.48",
    },
    {
      id: 1,
      image: productImg,
      title: "Graphic Design",
      department: "English Department",
      price: "$16.48",
      salePrice: "$6.48",
    },
    {
      id: 1,
      image: productImg,
      title: "Graphic Design",
      department: "English Department",
      price: "$16.48",
      salePrice: "$6.48",
    },
    {
      id: 1,
      image: productImg,
      title: "Graphic Design",
      department: "English Department",
      price: "$16.48",
      salePrice: "$6.48",
    },
    {
      id: 1,
      image: productImg,
      title: "Graphic Design",
      department: "English Department",
      price: "$16.48",
      salePrice: "$6.48",
    },
    {
      id: 1,
      image: productImg,
      title: "Graphic Design",
      department: "English Department",
      price: "$16.48",
      salePrice: "$6.48",
    },
    {
      id: 1,
      image: productImg,
      title: "Graphic Design",
      department: "English Department",
      price: "$16.48",
      salePrice: "$6.48",
    },
    // {
    //   id: 1,
    //   image: productImg,
    //   title: "Graphic Design",
    //   department: "English Department",
    //   price: "$16.48",
    // },
    // {
    //   id: 1,
    //   image: productImg,
    //   title: "Graphic Design",
    //   department: "English Department",
    //   price: "$16.48",
    // },
    // {
    //   id: 1,
    //   image: productImg,
    //   title: "Graphic Design",
    //   department: "English Department",
    //   price: "$16.48",
    // },
    // {
    //   id: 1,
    //   image: productImg,
    //   title: "Graphic Design",
    //   department: "English Department",
    //   price: "$16.48",
    // },
  ],
};

export default cartData;
