import productImg from "../assets/ProductCard/product-cover-5 (1).png";

const cartData = {
  data: [
    {
      // id: 1,
      department: "English Department",
      price: 16.48,
      salePrice: 6.48,
      title: "Graphic Design",
      image: productImg,
    },
    {
      // id: 1,
      department: "English Department",
      price: 16.48,
      salePrice: 6.48,
      title: "Graphic Design",
      image: productImg,
    },
    {
      // id: 1,
      department: "English Department",
      price: 16.48,
      salePrice: 6.48,
      title: "Graphic Design",
      image: productImg,
    },
    {
      // id: 1,
      department: "English Department",
      price: 16.48,
      salePrice: 6.48,
      title: "Graphic Design",
      image: productImg,
    },
    {
      // id: 1,
      department: "English Department",
      price: 16.48,
      salePrice: 6.48,
      title: "Graphic Design",
      image: productImg,
    },
    {
      // id: 1,
      department: "English Department",
      price: 16.48,
      salePrice: 6.48,
      title: "Graphic Design",
      image: productImg,
    },
    {
      // id: 1,
      department: "English Department",
      price: 16.48,
      salePrice: 6.48,
      title: "Graphic Design",
      image: productImg,
    },
    {
      // id: 1,
      department: "English Department",
      price: 16.48,
      salePrice: 6.48,
      title: "Graphic Design",
      image: productImg,
    },
    {
      // id: 1,
      department: "English Department",
      price: 16.48,
      salePrice: 6.48,
      title: "Graphic Design",
      image: productImg,
    },
    {
      // id: 1,
      department: "English Department",
      price: 16.48,
      salePrice: 6.48,
      title: "Graphic Design",
      image: productImg,
    },
    // {
    //   id: 1,
    //   image: productImg,
    //   title: "Graphic Design",
    //   department: "English Department",
    //   price: "$16.48",
    // },
    // {
    //   id: 1,
    //   image: productImg,
    //   title: "Graphic Design",
    //   department: "English Department",
    //   price: "$16.48",
    // },
    // {
    //   id: 1,
    //   image: productImg,
    //   title: "Graphic Design",
    //   department: "English Department",
    //   price: "$16.48",
    // },
    // {
    //   id: 1,
    //   image: productImg,
    //   title: "Graphic Design",
    //   department: "English Department",
    //   price: "$16.48",
    // },
  ],
};

export default cartData;
